# Generated by Django 2.2.2 on 2019-06-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pontoturistico_atracoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='atracoes',
            field=models.ManyToManyField(to='comentarios.Comentario'),
        ),
    ]
