# Generated by Django 2.2.2 on 2019-06-17 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='logitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
